name: Trigger Daily Job

on:
  schedule:
    - cron: "0 0 * * *"  # Every day at 00:00 UTC
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  run-jar-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Restore cache for visited.txt
        uses: actions/cache/restore@v4
        id: restore-cache
        with:
          path: visited.txt
          key: visited-cache-dummy-key
          # this is actual key. it finds latest visited.txt file
          restore-keys: |
            visited-cache-${{ runner.os }}-

      - name: Run JAR file
        run: |
          TARGET=$(find bin/ -name "*.jar")
          java -jar $TARGET -p visited.txt
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECIPIENT:  ${{ secrets.EMAIL_RECIPIENT }}

      - name: Save cache for visited.txt
        uses: actions/cache/save@v4
        # save if file is changed or not exists
        if: ${{ steps.restore-cache.outputs.cache-matched-key != format('visited-cache-{0}-{1}', runner.os, hashFiles('visited.txt')) }}
        with:
          path: visited.txt
          key: visited-cache-${{ runner.os }}-${{ hashFiles('visited.txt') }}  # Save new cache based on file hash
